stateDiagram-v2
    [*] --> AUTO

    state AUTO {
        [*] --> NS_GREEN
        NS_GREEN --> NS_YELLOW: 8s mac dinh
        NS_YELLOW --> EW_GREEN: 3s mac dinh
        EW_GREEN --> EW_YELLOW: 8s mac dinh
        EW_YELLOW --> NS_GREEN: 3s mac dinh
    }

    AUTO --> NIGHT: SET_NIGHT
    AUTO --> PRIORITY_NS: SET_PRIORITY_NS
    AUTO --> PRIORITY_EW: SET_PRIORITY_EW
    AUTO --> EMERGENCY: SET_EMERGENCY
    AUTO --> MAINTENANCE: SET_MAINTENANCE

    NIGHT --> AUTO: SET_AUTO
    NIGHT --> EMERGENCY: SET_EMERGENCY
    NIGHT --> MAINTENANCE: SET_MAINTENANCE

    PRIORITY_NS --> AUTO: SET_AUTO
    PRIORITY_NS --> EMERGENCY: SET_EMERGENCY
    PRIORITY_NS --> MAINTENANCE: SET_MAINTENANCE

    PRIORITY_EW --> AUTO: SET_AUTO
    PRIORITY_EW --> EMERGENCY: SET_EMERGENCY
    PRIORITY_EW --> MAINTENANCE: SET_MAINTENANCE

    EMERGENCY --> AUTO: SET_AUTO
    EMERGENCY --> NIGHT: SET_NIGHT
    EMERGENCY --> MAINTENANCE: SET_MAINTENANCE

    MAINTENANCE --> AUTO: SET_AUTO
