stateDiagram-v2

[*] --> AUTO_NS_GREEN


AUTO_NS_GREEN --> AUTO_NS_YELLOW

AUTO_NS_YELLOW --> AUTO_EW_GREEN

AUTO_EW_GREEN --> AUTO_EW_YELLOW

AUTO_EW_YELLOW --> AUTO_NS_GREEN


AUTO_NS_GREEN --> NIGHT

NIGHT --> AUTO_NS_GREEN


AUTO_NS_GREEN --> PRIORITY_NS

PRIORITY_NS --> AUTO_NS_GREEN


AUTO_EW_GREEN --> PRIORITY_EW

PRIORITY_EW --> AUTO_NS_GREEN


AUTO_NS_GREEN --> EMERGENCY

AUTO_EW_GREEN --> EMERGENCY

NIGHT --> EMERGENCY


EMERGENCY --> AUTO_NS_GREEN